services:
  - docker:dind

stages:
  - build

before_script:
  - docker info

build-job:
  stage: build
  image: docker:statble
  script:
    - docker build -t ingru/ingru-official-web .
  only:
    - docker-deploy
  tags:
    - docker-runner-docker
  cache:
    paths:
      - node_modules