name: Deploy to Server

on:
  push:
    branches:
      - release  # 触发流水线的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出分支
      - name: Checkout Repository
        uses: actions/checkout@v2

      # npm安装和打包成dist
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # rsa连接服务器来复制文件
      - name: Copy dist to Server
        uses: appleboy/scp-action@master
        run: |
          scp -i ${{ secrets.HOST_SSH_RSA_KEY }} -r dist/ root@ingru.cn:/etc/nginx/html/ingru_official_web

      # rsa连接服务器来更新nginx和其他重载操作
      - name: Update Nginx Configuration
        uses: appleboy/ssh-action@master
        with:
          host: ingru.cn
          username: root
          key: ${{ secrets.HOST_SSH_RSA_KEY }}
          script: |
            docker exec -it nginx bash
            nginx -s reload
